### ISSUE TITLE
mention the script in the Private and public subnets in a Virtual Private Cloud tutorial

### ISSUE THREAD

**Issue by powellquiring** [ibm-cloud-docs/tutorials#35]
https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-vpc-public-app-private-backend#vpc-public-app-private-backend

Private and public subnets in a Virtual Private Cloud

There is a script in the github repository: https://github.com/IBM-Cloud/vpc-tutorials/tree/master/vpc-public-app-private-backend that should be mentioned in the tutorial.

**Comment by l2fprod** [comment]
will integrate in future update
