### ISSUE TITLE
Change name and logo of database from "Compose MySQL" to "MySQL"

### ISSUE THREAD

**Issue by ljnoonan** [ibm-cloud-docs/tutorials#38]
Please change the diagram and any text references in this tutorial from  "Compose for MySQL" to "MySQL" .  You can use the MySQL logo found here. https://www.mysql.com/about/legal/logos.html

Compose for MySQL is no longer a brand used. 
 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/54455556/63623531-70003d00-c5bf-11e9-80e9-92ba416f3661.png">

**Comment by data-henrik** [comment]
The tutorial uses this service and its related icon from the IBM Cloud catalog: https://cloud.ibm.com/catalog/services/compose-for-mysql

Right now it is still labeled as "Compose for MySQL"

**Comment by l2fprod** [comment]
tutorial https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-vm-to-containers-and-kubernetes#vm-to-containers-and-kubernetes has been updated -- changes should go live soon

the screenshot seems to be from a marketing page. please reach out on slack (@fredl)
