### ISSUE TITLE
Unable to Retrieve Auto AI Deployments on Watson OpenScale

### ISSUE THREAD

**Issue by smruthi33** [ibm-cloud-docs/tutorials#39]
Hi I came across this article, that uses Auto AI deployments in OpenScale- https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-create-deploy-retrain-machine-learning-model
So, I re-tested using the same specs as mentioned- 
1) Choose Accuracy as the Optimised metric.
2) On the subsequent page, click on Configure source then Set Holdout data split to 25% and click Save. (Not sure if this was needed but I did it just in case)

However, I am unable to view my Auto AI deployment on Watson OpenScale Cloud and Watson OpenScale on CP4D 2.1.0.2 (AIOS 437), August release.

The Auto AI deployments are Tower C and Tower D-
<img width="1280" alt="screenshot 2019-09-06 at 1 52 21 pm" src="https://media.github.ibm.com/user/181777/files/ae145b00-d0ad-11e9-905d-ba041f561e7d">

Which are not visible in the latest OpenScale on Cloud-
<img width="1276" alt="screenshot 2019-09-06 at 1 50 09 pm" src="https://media.github.ibm.com/user/181777/files/583fb300-d0ad-11e9-8dfd-f232b1805fa7">

**Comment by l2fprod** [comment]
^ @VidyasagarMSC
