### ISSUE TITLE
Link for mapping custom domain to IBM cloud system domain is broken

### ISSUE THREAD

**Issue by anillewi** [ibm-cloud-docs/tutorials#44]
The link https://cloud.ibm.com/docs/infrastructure/cis?topic=solution-tutorials-multi-region-webapp#alternative-map-the-custom-domain-to-the-ibm-cloud-system-domain in https://cloud.ibm.com/docs/infrastructure/cis?topic=solution-tutorials-multi-region-webapp is broken. I am assuming it needs to be https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-custom-domains#mapcustomdomain. Also the route information should be <Name>.<Your Custom domain> instead of <your app>.<your domain name>

**Comment by data-henrik** [comment]
Which page has the broken link and in what section? Thank you for raising an issue.

**Comment by anillewi** [comment]
Page https://cloud.ibm.com/docs/infrastructure/cis?topic=solution-tutorials-multi-region-webapp has the broken link. The section containing the broken link is Alternative: Map the custom domain to the IBM Cloud system domain. Link that is broken is "[list of domains in the Cloud Foundry organization where the applications are deployed](https://cloud.ibm.com/docs/apps?topic=creating-apps-updatingapps#updatingapps)".

**Comment by data-henrik** [comment]
Got it, thank you! I verified that it is broken.

**Comment by data-henrik** [comment]
The updated links are available in the tutorial now:
- https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-multi-region-webapp (primary)
- https://cloud.ibm.com/docs/infrastructure/cis?topic=solution-tutorials-multi-region-webapp
