### ISSUE TITLE
 vpc-pubpriv

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/tutorials#45]
This is not a valid VPC name in this link:
https://cloud.ibm.com/docs/vpc-on-classic?topic=solution-tutorials-vpc-public-app-private-backend

**Comment by data-henrik** [comment]
Could you provide more information on what you mean? Which tutorial are you referring to? What name is not valid and where?

**Comment by l2fprod** [comment]
please reopen if this is still a problem
