### ISSUE TITLE
vpc-secure-bastion-subnet 

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/tutorials#46]
vpc-secure-bastion-subnet is not a valid name in this link:
https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-vpc-secure-management-bastion-server#create-configure-security-group

**Comment by data-henrik** [comment]
Could you provide some more context / details about the issue? Is the name not a valid identifier or is the name missing?

**Comment by l2fprod** [comment]
please reopen if this is still a problem
