### ISSUE TITLE
Wants to Charge Me

### ISSUE THREAD

**Issue by jimi-thompson** [ibm-cloud-docs/tutorials#47]
I'm not able to complete the tutorial because it wants to charge me.  I know that IaaS has test accounts that don't actually bill anyone.  Is it possible to do this with PaaS?

**Comment by l2fprod** [comment]
@jimi-thompson 

which tutorial are you looking at? as the tutorials involve several services and advanced features, most will incur cost.

**Comment by jimi-thompson** [comment]
If that's the case, I won't be able to do them.

Thanks,

Jimi Thompson, MBA, CISSP, PMP, LPIC-1, Fortinet NSE 3
Senior Support Manager & Country Manager
Softlayer AMS Support Center
Johan Huizingalaan 765
1066 VH Amsterdam, Netherlands
jimi.thompson1@nl.ibm.com
https://ibm.biz/IaaS_Support
"Money may not buy happiness but it will get you all the warm snuggly
puppies you want and warm snuggly puppies make most people happy."- Me
