### ISSUE TITLE
node actions of type web_action not documented. Obsolete?

### ISSUE THREAD

**Issue by ftram** [ibm-cloud-docs/tutorials#48]
The tutorial [Build a database-driven Slackbot](https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-slack-chatbot-database-watson) provides the json file of the dialog skill.
In three nodes web_action actions are defined, used to call IBM Cloud Function web actions.
But I haven't found any documentation on the web_action type of actions definable in the dialog nodes.
I have only found documentation on the [actions of type "client"](https://cloud.ibm.com/docs/services/assistant?topic=assistant-dialog-actions-client) and on the [webhooks](https://cloud.ibm.com/docs/services/assistant?topic=assistant-dialog-webhooks).
Maybe this type of actions are obsolete or not supported anymore, since now we have the webhooks?

**Comment by data-henrik** [comment]
They were previously documented and seem to have been removed. I am currently following up with the documentation team.

**Comment by data-henrik** [comment]
On August 1st, Watson Assistant introduced webhooks support: https://cloud.ibm.com/docs/services/assistant?topic=assistant-release-notes#1August2019

> Webhook callouts are available: Add webhooks to dialog nodes to make programmatic calls to an external application as part of the conversational flow. The new Webhook support simplifies the callout implementation process. (No more action JSON objects required.)

Previously, action could only be defined in the JSON object for a dialog node. You can still see the (now deleted) documentation here:
https://github.com/ibm-cloud-docs/assistant/blob/6eca3672cc7085ee3921acfb3d9729baf101e254/dialog-actions.md

I am following up with the Watson Assistant team on how to proceed. Stay tuned.

**Comment by data-henrik** [comment]
The tutorial has been updated and the code rewritten to use webhooks instead of web_action. Webhooks were introduced earlier this year and are the way to go forward.
https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-slack-chatbot-database-watson#build-a-database-driven-slackbot

https://github.com/IBM-Cloud/slack-chatbot-database-watson
