### ISSUE TITLE
The options, embedded links, images and buttons not working

### ISSUE THREAD

**Issue by SimNee** [ibm-cloud-docs/tutorials#49]
![image](https://user-images.githubusercontent.com/47185582/70972506-78383700-20de-11ea-9bb2-a92cd6932683.png)
![image](https://user-images.githubusercontent.com/47185582/70972588-b2093d80-20de-11ea-90ae-78cee503d20c.png)
The first image represents the IBM Watson Chatbot when deployed on Andriod Studios Emulator. The options features are not being displayed properly whereas the second image shows the chatbot on the preview link from IBM Watson whereby the options are clearly shown. The application was done following the IBM Watson's tutorial at this link: https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-android-watson-chatbot#build-a-voice-enabled-android-chatbot

**Comment by VidyasagarMSC** [comment]
@SimNee The code is updated. Options don't appear as a dropdown or combo but can be used as text input.
