### ISSUE TITLE
Solution tutorial: updates for new flow

### ISSUE THREAD

**Issue by vwilburn** [ibm-cloud-docs/tutorials#50]
I saw a couple discrepancies while running through this tutorial:
https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-scalable-webapp-openshift#services

1) Prerequisite steps didn't say you need a GitLab account before you generate SSH key. SSH key instructions weren't clear which type of key pair was required. Was a "deploy" type needed? SSH setup also didn't provide name to replace in this command: `replacing gitlab.com with your GitLab's instance domain` 
2) Prerequisites duplicated. 3rd step linked to installing ibmcloud cr command, but first step installs ibmcloud cr plugin. "Install IBM Cloud Developer Tools - Script to install docker, kubectl, ibmcloud cli and required plug-ins like dev, ks, cr ..."
3) Create cluster page has different order than the steps listed in "Create an OpenShift cluster".

**Comment by vwilburn** [comment]
also:
- The following Tip says to target org and space, but the CLI doesn't explain how you figure out the names of the org/space or why an OpenShift tutorial needs to use Cloud Foundry. 
"You may be asked to target an organization and a space, follow the instructions on the CLI."

**Comment by vwilburn** [comment]
- The following step tells the user to select "Node.js Web App with Express.js", but that is not an option from the ibmcloud dev command wizard:
"Select Backend Service / Web App then Node and select Node.js Web App with Express.js to create a Node starter."

**Comment by l2fprod** [comment]
there is no need for a _GitLab_ (gitlab.com) account - the tutorial refers to  an account in IBM Cloud Git hosting (powered by GitLab), it comes with your IBM Cloud IBMid. We only make sure it is properly configured with an SSH key in the tutorial.

**Comment by l2fprod** [comment]
about CF org/space, this is a requirement of "dev create" even though it won't use the CF org and space today. I'll add this to the tip. We can't avoid this configuration right now.

**Comment by vwilburn** [comment]
Perhaps the wording about setting up git needs to indicate how the account works when you use GitLab. I think the nugget that could be added is as you said: 
`Access GitLab with your IBM Cloud IBMid.`

**Comment by l2fprod** [comment]
reorganized the create cluster steps

**Comment by l2fprod** [comment]
applied changes, will show in next push to production

**Comment by vwilburn** [comment]
- New users such as ones who do tutorials might not know that this command required the API key pasted in for _$API_KEY_. At least that's what I guessed to do, given the lack of angle brackets or italics in the text. 
oc create secret docker-registry push-secret --docker-username=iamapikey --docker-password=$API_KEY --docker-server=$MYREGISTRY

- The generated openshift.yaml file has two sections with `kind: ImageStream`, so it's not clear which section requires the edits for namespace and project name. It took a lot of slow, careful comparison to figure out which section to update. Is there a way to make finding the section more easily? Same comments as above about using the `$` nomenclature to indicate a variable that requires replacement. Some people might literally search on those strings in the yaml. 

- The DockerImage uri requires a `.git` at the end for it to work for me. This is something a ROKS developer suggested and was also suggested in Google searches. See this step for reference: "Update the spec under BuildConfig section by changing the output to kind DockerImage and adding a pushSecret"

- After running the oc logs command, discovered that Dockerfile had newer syntax for chown that seems to be unsupported by older OpenShift 3x. A ROKS developer hand-hacked the DockerFile to use `RUN chown 1001:1001 /app/`

**Comment by l2fprod** [comment]
1. I changed the step to set the API_KEY env variable - this was missing. so then the command works with no change

2. unless we provide scripts to manipulate the yaml, asking to search for the ImageStream where the name attribute is your project name is the way to go

**Comment by l2fprod** [comment]
- I had the "chown" issue too -- seems to be linked to a change in what _ibmcloud dev_ produces

- I did not need to put .git in the Docker image URI

**Comment by vwilburn** [comment]
Couple more items:

- In "Use your own custom domain," the prereqs could be more strongly stated that users must have access to their company's or personal domain DNS (if one even exists). Step 2 could also be clearer about the format for the resulting URL, for example what goes after the domain: project name, namespace...?

- In the Monitoring step that says "click Execute to see the total container cpu usage in seconds on a Graph and a console." I could see data in the Graph tab on Prometheus but not data for the Console tab. Perhaps the Monitoring task should have a prereq that says you have to know how to use Grafana and Prometheus, since these steps don't provide enough detail to figure out what users are looking at.
