### ISSUE TITLE
"Extensions" entry is not available in Watson IoT left menu

### ISSUE THREAD

**Issue by bodiroga** [ibm-cloud-docs/tutorials#52]
Hi docs team!

First of all, many thanks for your cloud platform and your awesome tutorials, they are very well documented :+1: 

I've been following the [Gather, visualize, analyze and detect anomalies in IoT data](https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-gather-visualize-analyze-iot-data) tutorial and, although I was able to go through it flawlessly, I'm stuck in the second step of the "Create a data connector to store the historical data" section. In my Watson IoT left menu, there is no entry called "Extensions", my last option is the "Configuration" one. As far as I know, I have re-checked all the steps twice and I have tried to configure different regions (I'm located in Spain) for both Watson IoT and cloudant services (all within the "Lite" program), but I can't, for the life of me, forward the data received in Watson IoT to Cloudant. This is what I currently see:

![image](https://user-images.githubusercontent.com/663065/74320125-61316080-4d80-11ea-926b-6826152c8958.png)

Is there anything that has changed in the Watson IoT platform since you wrote the tutorial? Do I need to activate anything in my account that allows me to see the "Extensions" option?

Thank you for your support and if you need more information about my setup, don't hesitate to ask.

Best regards,

Aitor

**Comment by VidyasagarMSC** [comment]
@bodiroga The tutorial is updated with the latest information. Feel free to open a new issue if you find any further issues.
