### ISSUE TITLE
Question about "functional user" in "Best practices for organizing users, teams, applications"

### ISSUE THREAD

**Issue by bennythejudge** [ibm-cloud-docs/tutorials#53]
I am referring to page:

https://github.com/ibm-cloud-docs/tutorials/blob/master/users-teams-applications.md

and in particular to the paragraph:

> To support the execution of the build pipeline, we introduce a functional user - a regular IBM Cloud user but a team member with no real identity in the physical world. This functional user will own the delivery pipelines and any other cloud resources requiring strong ownership. This approach helps in the case where a team member leaves the company or is moving to another project. The functional user will be dedicated to your project and will not change over the lifetime of the project. The next thing you will want to create is an API key for this functional user. You will select this API key when you setup the DevOps pipelines, or when you want to run automation scripts, to impersonate the functional user

IMVHO this looks like a use case for a `serviceId`. What do you think? Why suggest using a regular user for a fictitious user?
Thanks

**Comment by data-henrik** [comment]
@bennythejudge Thank you for the feedback. I have created an internal defect with your feedback. The tutorial is being reworked.

The concept of serviceID was introduced after that tutorial was written. serviceID is the way to go today IMHO.

**Comment by l2fprod** [comment]
updated the tutorial. next update will include the changes.
