### ISSUE TITLE
Broken link in tutorial "Best practices for organizing users, teams, applications"

### ISSUE THREAD

**Issue by bennythejudge** [ibm-cloud-docs/tutorials#54]
I am referring to paragraph:

https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-users-teams-applications#related-information

The link 
https://cloud.ibm.com/docs/services/Monitoring-with-Sysdig?topic=Sysdig-iam_work
is broken it gives 404.

**Comment by data-henrik** [comment]
Thank you for the feedback. The link should be https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Sysdig-iam

I have opened an internal feedback to address the issue in the source.

**Comment by l2fprod** [comment]
fixed in https://github.com/ibm-cloud-docs/tutorials/commit/ba69169ce1b975c46a897ecdad62dd57f630b28e
