### ISSUE TITLE
The link for Get Started is broken on the Moving a VM based app to Kubernetes

### ISSUE THREAD

**Issue by joebarrera** [ibm-cloud-docs/tutorials#55]
Here is the bad link that is set on the page https://developer.ibm.com/courses/all/get-started-kubernetes-ibm-cloud-container-service/

The page URL that contains the bad link is :https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-vm-to-containers-and-kubernetes

**Comment by l2fprod** [comment]
thank you

https://developer.ibm.com/gettingstarted/containers/ will be a good replacement

**Comment by l2fprod** [comment]
will come with next update
