### ISSUE TITLE
Creating a Cloudant binding does not work.

### ISSUE THREAD

**Issue by eu-barbu** [ibm-cloud-docs/tutorials#56]
I tried to make this example. When I arrive at this step:
"For Cloudant Instance, select Input your own credentials and fill in the following fields with the credentials information captured for your cloudant service: Username, Password, Host and Database = guestbook and click Add and then Save."

After I insert my credentials for the Cloudant database and click on Add, I am redirected to the sequence overview, without receiving any error or confirmation message. Saving the bindings is not possible. When I recheck the binding, which was just added to the sequence, I have the message: "You do not currently have any existing bindings for this package". Can you tell how to fix this? Thanks

![fn1](https://user-images.githubusercontent.com/60646398/77821748-4b3feb00-70f5-11ea-9329-3f459dfa1347.PNG)
![fn2](https://user-images.githubusercontent.com/60646398/77821750-4d09ae80-70f5-11ea-9b82-29043f44f928.PNG)
![fn3](https://user-images.githubusercontent.com/60646398/77821763-66125f80-70f5-11ea-94b5-58b9b1752a25.PNG)

**Comment by eu-barbu** [comment]
This is the tutorial I tried:
https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-serverless-api-webapp#serverless-api-webapp

**Comment by l2fprod** [comment]
@eu-barbu 

Thank you, I could reproduce the problem and raised the issue to our Cloud Functions team. Will keep you posted here.

**Comment by l2fprod** [comment]
@eu-barbu 

we updated the instructions to allow you to create the binding and get that "Save" button enabled:
![image](https://user-images.githubusercontent.com/12746550/78686949-3ca5c080-78b9-11ea-8002-9cec54c74cb8.png)
