### ISSUE TITLE
apiVersion deprecated in k8s 1.16

### ISSUE THREAD

**Issue by maxisses** [ibm-cloud-docs/tutorials#57]
Hey there,
The tutorial https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-pub-sub-object-storage doesn't seem to work with k8s 1.16:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
K8s apiVersion has to be upgraded and the selector tag is required to make it work I think.

It is also worth specifiying that only helm v2 works with "ibm cloud deploy". Helm init is not available in helm v3.

Best,
Max

**Comment by data-henrik** [comment]
@maxisses we are going to look into it and then update the tutorial - thank you

**Comment by VidyasagarMSC** [comment]
@maxisses The update to the tutorial should be available by End of day today. Closing this issue for now. Please check and do reopen if necessary. Thanks
